### PR TITLE
Add SNI, remove network operations from UI thread, and make certificate not required anymore, add gradle support

### PR DESCRIPTION
**Pull request by moparisthebest**
These commits fix a few issues stopping this from running on cyanogenmod 12.1 which is android 5.1, and adds SNI in a way that is supported on many phones back to android 2.3.

I also didn't want the certificate to be required, and plan to add different certificate authentication methods in the future such as pinned public key or regular verification using CAs.

Lastly, I'd like to thank you for this great piece of software, and would also like to ask/request you to put an Open Source license on it, I personally prefer GPL, but Apache or similar would be great too?

### CODE REVIEW

**Comment by blint** [comment]
Wow, thanks for this! 

If you don't mind, I'll break it into two commits to separate the feature and the changes induced by the API level change. Did you have a chance to use the app for a longer time with the server socket moved off the UI thread? I had a rudimentary solution like that, but in this case, I had some threading issues in the emulator.

You can consider SSLDroid as GPLv2, I'll add the license statement to the files as soon as I find the time. Thanks again for the contribution!

**Comment by moparisthebest** [comment]
Yes, breaking it up makes sense, I didn't have any certificates so I had to make those changes to test my other changes.

I have been using it since I made these changes to connect to SSH and IRC over a TLS tunnel from my phone with no issues, if it helps I'm running it on Cyanogenmod 12.1 (Android 5.1) on a Samsung Galaxy S4.

The IDE can put a license statement on all files automatically, but even slapping [this](https://www.gnu.org/licenses/gpl-2.0.txt) in the root of the repo as LICENSE or something would clarify everything and qualify this to be built for the f-droid market and such, so people like me who don't have google play installed can have access! :)

**Comment by blint** [comment]
I had the same thing on the refactor branch, so I feel the pain :) 

Great, might be some emulator issue then, wouldn't have made sense based on the code change but I've seen weird things around 2.3. Many thanks, that should do it I think, most of the users (based on Play stats) are using 4.0+ anyway.

I've pushed the changes to the moparisthebest-sni branch, can you please take a quick look? If everything seems OK, I'll merge it to master and release to beta on Play.

Great idea, added LICENSE on the same branch :)

**Comment by moparisthebest** [comment]
I checked out, built, and tested the moparisthebest-sni branch and it works for me.

Thanks!

**Comment by blint** [comment]
Thanks again for the contribution and the help!

**Pull request closed without merging**
